### ISSUE TITLE
Testy: QT rzeczy

### ISSUE THREAD

**Issue by Riyria-was-taken** [Lorak-mmk/EchoConnect#45]

**Comment by Lorak-mmk** [comment]
Zostaną zrobione jeśli wymyślę jak, jednak nie jest to obowiązkowy punkt sprintu

**Comment by Lorak-mmk** [comment]
Sensowne przetestowanie tego wymagałoby zamockowania tak naprawdę calej funkcjonalności QAudioInput/Output, QAudio, QAudioFormat, a także zapewne użycia dodatkowych bibliotek, do konwertowania między różnymi formatami dźwięku, a i tak takie testy niewiele by sprawdzały.
