### ISSUE TITLE
Przygotowanie CI dla Windowsa i MacOS

### ISSUE THREAD

**Issue by Riyria-was-taken** [Lorak-mmk/EchoConnect#50]

**Comment by Lorak-mmk** [comment]
https://stackoverflow.com/questions/44739411/clion-qt5-exit-code-1073741515-0xc0000135

**Comment by Lorak-mmk** [comment]
Póki co bez testów na windowsie, tylko budowanie, bo problemy z ładowaniem dll. Testy dodam w przyszłości.
